### ISSUE TITLE
The number of seconds in a minute is not fixed

### ISSUE THREAD

**Issue by ragmondo** [kunalsheth/units-of-measure#4]
https://github.com/kunalsheth/units-of-measure/blob/63cc2baad35384d8a3bdf3dbbf29e6082683a9d1/demo/src/main/kotlin/info/kunalsheth/units/sample/Sample.kt#L25

A minute can be 61 or 59 seconds. Just thought you should know. https://en.wikipedia.org/wiki/Minute

**Comment by kunalsheth** [comment]
Hi Richard, thanks for bringing this up. I originally designed this library for robotics/engineering applications ([FRC](https://www.firstinspires.org/robotics/frc)) where "leap-time" doesn't really matter. May I ask where you are using this such that you do need to account for leap-seconds?

I designed this library to be extendible, but I never thought of this case. I guess you can add in another unit to your gradle configuration: `unitsOfMeasure += u("LeapSecond", 61.0 / 60, d(T = 1))`
I don't know enough about your use case to tell if this is okay, for example, are 60 leap-seconds supposed to equal one minute?

Because I've never had to deal with leap-time, I'm not sure how I'ld go about implementing this as a feature. Do you know of any libraries which can handle these calculations?
